version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"            # LocalStack endpoint
#      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack-script:/docker-entrypoint-initaws.d
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

