spring:
  config:
    import:
      - aws-secretsmanager:/secret/commercial/webhooks/cust1?prefix=foo.
      - aws-secretsmanager:/secret/commercial/webhooks/cust2?prefix=hoo.

test:
  userinfo: ${foo.username}