spring:
  config:
    import:
      - aws-secretsmanager:/secret/commercial/webhooks/cust1?prefix=foo.
      - aws-secretsmanager:/secret/commercial/webhooks/cust2?prefix=hoo.

test:
  userinfo: ${foo.username}

aws:
  secretsmanager:
    fail-fast: false
    endpoint: https://localhost.localstack.cloud:4566
